[build]
  command = "npm run build"
  publish = "dist/trustvault-core/browser" # Ensure this matches your angular.json output path
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
